Test executables with excheck function, including unzip version Many doc and syntax changes

diff --git a/backup b/backup
--- a/backup
+++ b/backup
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-Version=3.17
+Version=3.18
 Myname="${0##*/}"
 
 :<<'DOC'
@@ -192,15 +192,13 @@ Note that:
 Released under the [GNU General Public License](www.gnu.org/copyleft/gpl.html)
 DOC
 
-:<<'DOC' #------ function configure --------------------------------------------
+:<<'DOC' #----------------------------------------------------------------------
 = configure
-parameters:	-
 description:	Sets the defaults, and then applies any changes defined in the 
 		configuration file if it exists (|/etc/backup.conf| by default)
 globals  set:	 BackupDir DirsToSearch DirReToSkip ExtReToSkip
 		 BaseReToSkip FileReToSkip conffile
 globals used:	 BackupDir conffile Myname
-returns:	0
 DOC
 #-------------------------------------------------------------------------------
 configure () {
@@ -262,13 +260,10 @@ configure () {
 }
 
 
-:<<'DOC' #------ function latestof ---------------------------------------------
+:<<'DOC' #----------------------------------------------------------------------
 = latestof
-parameters:	1: fileglob
+synopsis:	 latestof fileglob
 description:	print the newest file matching the fileglob
-globals  set:	-
-globals used:	-
-returns:	-
 DOC
 #-------------------------------------------------------------------------------
 latestof () {
@@ -280,9 +275,8 @@ latestof () {
    echo "$latest"
 }
 
-:<<'DOC' #------ function setselector ------------------------------------------
+:<<'DOC' #----------------------------------------------------------------------
 = setselector
-parameters:	-
 description:	Find the last full or (if the |--full| option was not used)
 		partial backup file: that file is the reference file: it's mtime
 		will be used, by setting selector to |-newer <file>|. If it's a
@@ -293,13 +287,12 @@ description:	Find the last full or (if the |--full| option was not used)
 		|fnnn.zip|, where |nnn| is one higher than that of the reference
 		file.
 globals  set:	 selector newbackup 
-globals used:	 full 
-returns:	1 if no backup file could be found.
+globals used:	 full named
 DOC
 #-------------------------------------------------------------------------------
 setselector () {
    verbo setselector
-   local lastfull lastpart
+   local lastfull lastpart n
    lastfull=$(latestof f[0-9][0-9][0-9].zip)
    if [ -z "$named" ]; then
       # full or partial backup:
@@ -308,7 +301,6 @@ setselector () {
       # named backup:
       lastpart=$(latestof [fpt][0-9][0-9][0-9].zip)
    fi
-   local n
    if $full; then
       selector=
       n=1$(tr -cd '[:digit:]' <<<"${lastfull:-000}")
@@ -324,13 +316,10 @@ setselector () {
    test -n "$named" && newbackup="$named.zip"
 }
 
-:<<'DOC' #------ function human ------------------------------------------------
+:<<'DOC' #----------------------------------------------------------------------
 = human
-parameters:	1: a number of bytes
+synopsis:	 human number_of_bytes
 description:	prints the number in human-readable form
-globals  set:	-
-globals used:	-
-returns:	0
 DOC
 #-------------------------------------------------------------------------------
 human () {
@@ -342,13 +331,9 @@ human () {
    echo "$s${u:$n:1}"  # human readable size
 }
 
-:<<'DOC' #------ function showbackups ------------------------------------------
+:<<'DOC' #----------------------------------------------------------------------
 = showbackups
-parameters:	-
 description:	show the current backups
-globals  set:	-
-globals used:	-
-returns:	0
 DOC
 #-------------------------------------------------------------------------------
 showbackups () {
@@ -372,15 +357,14 @@ showbackups () {
    exit
 }
 
-:<<'DOC' #------ function backupsof --------------------------------------------
+:<<'DOC' #----------------------------------------------------------------------
 = backupsof
-parameters:	1: filename in current directory
+synopsis:	 backupsof filename
 description:	Find basenames, without extension, of all archives containing
 		the given filename. Store them, with the size and time
 		information, in backupsfound.
 globals  set:	 backupsfound 
-globals used:	-
-returns:	0
+globals used:	 workdir
 DOC
 #-------------------------------------------------------------------------------
 backupsof () {
@@ -397,17 +381,13 @@ backupsof () {
    done
 }
 
-:<<'DOC' #------ function extract ----------------------------------------------
+:<<'DOC' #----------------------------------------------------------------------
 = extract
-parameters:	1: filename = name of the file to extract
-		2:        i = index in |${backupsfound[@]}|
-		3: withdate = true if date must be appended to filename
-description:	extract |$workdir/filename| from the ith element of
-		|$backupsfound| appending the date of the element if
-		withdate is true
-globals  set:	 -
+synopis:	extract filename index withdate
+description:	extract |$workdir/filename| from the |index|th element of
+		|backupsfound| appending the date of the element if
+		|withdate| is true
 globals used:	 BackupDir backupsfound workdir
-returns:	 0
 DOC
 #-------------------------------------------------------------------------------
 extract () {
@@ -425,13 +405,12 @@ extract () {
    touch -t "${date/-/}" "$out"
 }
 
-:<<'DOC' #------ function restore ----------------------------------------------
+:<<'DOC' #----------------------------------------------------------------------
 = restore
-parameters:	1: basename of file in current directory
-description:	Restore the given file in the current directory
+synopsis:	 restore filename
+description:	Restore the given filename in the current directory
 globals  set:	 COLUMNS 
 globals used:	 backupsfound REPLY workdir
-returns:	0
 DOC
 #-------------------------------------------------------------------------------
 restore () {
@@ -468,12 +447,9 @@ restore () {
    esac
 }
 
-:<<'DOC' #------ function updatelistings ---------------------------------------
+:<<'DOC' #----------------------------------------------------------------------
 = updatelistings
-parameters:	-
 description:	Update archive listings where necessary
-globals used:	-
-returns:	0
 DOC
 #-------------------------------------------------------------------------------
 updatelistings () {
@@ -486,13 +462,12 @@ updatelistings () {
    shopt -u nullglob
 }
 
-:<<'DOC' #------ function list -------------------------------------------------
+:<<'DOC' #----------------------------------------------------------------------
 = list
-parameters:	1: name of archive to be listed
+synopsis:	 list archive
 description:	Create a listing, sorted by decreasing size, of the contents of
 		the archive. Set the modification time of the archive and its
 		listing to to the most recent regular file in the archive.
-returns:	0
 DOC
 #-------------------------------------------------------------------------------
 list () {
@@ -502,31 +477,27 @@ list () {
       grep -av /$ ".$f" | # directories
       sed 's/^  *//;s/[0-9]\+  //;s/   .*//'| # keep dates only
       sort -r|head -1 # use most recent
-   ):59" "$f".zip ."$f" || die "Your unzip ($(command -v unzip)) is too old"
+   ):59" "$f".zip ."$f"
    # ^^ fills in the missing seconds
 }
 
-:<<'DOC' #------ function verbo ------------------------------------------------
+:<<'DOC' #----------------------------------------------------------------------
 = verbo
-parameters:	*: message
-description:	print the argument(s) to standard error, if |$verbose| is true
-globals  set:	-
+synopsis:	 verbo message [message...]
+description:	print the argument(s) to standard error, if |verbose| is true
 globals used:	 verbose
-returns:	0
 DOC
 #-------------------------------------------------------------------------------
 verbo() {
    $verbose && echo "$*"
 } 1>&2
 
-:<<'DOC' #------ function verbarr ----------------------------------------------
+:<<'DOC' #----------------------------------------------------------------------
 = verbarr
-parameters:	1: name of an array variable
+synopsis:	 verbarr name_of_array_variable
 description:	echo the name of the variable plus a colon and the array
 		contents in two columns of width 15 and 50 respectively.
-globals  set:	-
 globals used:	 verbose
-returns:	0
 DOC
 #-------------------------------------------------------------------------------
 verbarr() {
@@ -537,79 +508,118 @@ verbarr() {
 	 sed '2,$s/^/               /;1,$s/$/ \\/;s/→ \\//'
 } 1>&2
 
-REd='\e[38;5;9m'
-    die() { local i; for i; do echo -e "$Myname: $REd$i"; done 1>&2; exit 1; }
+:<<'DOC' #----------------------------------------------------------------------
+= excheck
+synopsis:	 excheck executable1 [executable2...]
+description:	check if all needed execs are there and getopt is GNU
+DOC
+#-------------------------------------------------------------------------------
+excheck() {
+   local ok=true i
+   for i; do 
+      command -v "$i" > /dev/null && continue
+      Warn "Missing executable: $i"
+      ok=false
+   done
+   $ok || die
+   getopt -T 
+   [[ $? -ne 4 ]] && die "Your getopt is not GNU"
+   i=$(unzip -h|head -1|cut -c7-10)
+   test ${i:0:1} -ge 6 || die "Your unzip is too old (version $i)"
+}
+
+:<<'DOC' #----------------------------------------------------------------------
+= handle_options
+synopsis:	 handle_options "$@"
+description:	Handle the options
+globals used:	 Myname Version full show restore conffile verbose named showdir
+DOC
+#-------------------------------------------------------------------------------
+handle_options() {
+   local options
+   if ! options=$(getopt \
+      -n "$Myname" \
+      -o hHVIc:fsr:vn:d \
+      -l help,Help,version,conf:,full,show,restore:,verbose,named:,dir,nocolor,web \
+      -- "$@"
+   ); then exit 1; fi
+   eval set -- "$options"
+   
+   full=false show=false restore='' conffile='' verbose=false named='' showdir=false
+   while [ $# -gt 0 ]; do
+      case $1 in
+      (-h|--help)		# print this help and exit
+   	helpsrt
+   	;;
+      (-H|--Help)		# print full documentation via less and exit
+   	helpall
+   	;;
+      (-V|--version)		# print version and exit
+   	echo $Version
+           exit
+   	;;
+      (-f|--full)		# make a full backup
+   	full=true
+   	shift 
+   	;;
+      (-s|--show)		# Show a listing of the current backups
+   	show=true
+   	shift
+   	;;
+      (-c|--conf)		# use |FILE| as the configuration file
+   	[[ $2 = - || -e $2 ]] ||
+   	die "The specified configuration file $2 does not exist"
+   	conffile="$2"
+   	shift 2
+   	;;
+      (-r|--restore)	# Restore |FILE| in current directory
+   	restore="$2"
+   	shift 2
+   	;;
+      (-v|--verbose)	# print intermediate messages for debugging
+   	verbose=true
+   	shift
+   	;;
+      (-n|--named)		# make partial backup to named |FILE|
+   	named="$2"
+   	[[ $named =~ ^[pf][[:digit:]]{3}$ ]] &&
+   	die "--named argument may not be pnnn or fnnn"
+   	shift 2
+   	;;
+      (-d|--dir)		# show the backup directory path and exit
+   	showdir=true
+           shift
+           ;;
+      (-I)
+   	instscript "$0" ||
+	   die 'the -I option is for developers only'
+        exit
+   	;;
+      (--)
+   	shift
+   	break
+   	;;
+      (*)
+   	break
+   	;;
+      esac
+   done
+}
+
+REd='\e[38;5;9m' Nor='\e[0m'
+    die() { local i; for i; do echo -e "$Myname: $REd$i$Nor"; done 1>&2; exit 1; }
 helpsrt() { sed -n '/^= Synopsis/,/^= /p' "$0"|sed '1d;$d'; exit; }
 helpall() { sed -n "/^:<<'DOC'$/,/^DOC/p" "$0"|sed -n '1d;$d;p'|
             less -Ps"$Myname-${Version/./·} documentation - type h for help, q to quit."
 		exit
 	  }
 
-if ! options=$(getopt \
-   -n "$Myname" \
-   -o hHVIc:fsr:vn:d \
-   -l help,Help,version,conf:,full,show,restore:,verbose,named:,dir,nocolor,web \
-   -- "$@"
-); then exit 1; fi
-eval set -- "$options"
-full=false show=false restore='' conffile='' verbose=false named='' showdir=false
-while [ $# -gt 0 ]; do
-   case $1 in
-   (-h|--help)		# print this help and exit
-	helpsrt
-	;;
-   (-H|--Help)		# print full documentation via less and exit
-	helpall
-	;;
-   (-V|--version)	# print version and exit
-	echo $Version
-        exit
-	;;
-   (-f|--full)		# make a full backup
-	full=true
-	shift 
-	;;
-   (-s|--show)		# Show a listing of the current backups
-	show=true
-	shift
-	;;
-   (-c|--conf)		# use |FILE| as the configuration file
-	[[ $2 = - || -e $2 ]] ||
-	die "The specified configuration file $2 does not exist"
-	conffile="$2"
-	shift 2
-	;;
-   (-r|--restore)	# Restore |FILE| in current directory
-	restore="$2"
-	shift 2
-	;;
-   (-v|--verbose)	# print intermediate messages for debugging
-	verbose=true
-	shift
-	;;
-   (-n|--named)		# make partial backup to named |FILE|
-	named="$2"
-	[[ $named =~ ^[pf][[:digit:]]{3}$ ]] &&
-	die "--named argument may not be pnnn or fnnn"
-	shift 2
-	;;
-   (-d|--dir)		# show the backup directory path and exit
-	showdir=true
-        shift
-        ;;
-   (-I)
-	instscript "$0"
-	exit
-	;;
-   (--)
-	shift
-	break
-	;;
-   (*)
-	break
-	;;
-   esac
-done
+# =============== Program starts here =============
+
+# Are all executables there?
+excheck getopt fold grep less sed tr unzip zip
+
+handle_options "$@"
 
 configure
 $showdir && echo "$BackupDir" && exit 0
